name: Bit verify

on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    container:
      image: bitsrc/stable:1.9.124-alpine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bit install
        env:
          BIT_CONFIG_USER_TOKEN: ${{ secrets.BIT_ACCESS_TOKEN }} 
      
      - name: List components
        run: bit list automations.design
        env:
          BIT_CONFIG_USER_TOKEN: ${{ secrets.BIT_ACCESS_TOKEN }} 

      - name: Verify workspace
        run: bit ci verify
        env:
          BIT_CONFIG_USER_TOKEN: ${{ secrets.BIT_ACCESS_TOKEN }} 